project:
  type: book
  output-dir: docs
book:
  title: "learningdiary"
  author: "Yizhuo Shi"
  date: "1/24/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

